---
# GNOME Customization Tasks

- name: Ensure unzip is installed
  apt:
    name: unzip
    state: present

# Define a temporary path in /tmp
- name: Set temporary download path variable
  set_fact:
    temp_font_dir_path: "/tmp/barlow_font_{{ 100000 | random }}"
    temp_font_zip_path: "/tmp/barlow_font_{{ 100000 | random }}.zip"

- name: Create temporary directory for font download in /tmp
  ansible.builtin.file:
    path: "{{ temp_font_dir_path }}"
    state: directory
    mode: '0777' # Ensure ansible user can write here

- name: Download Barlow font files from GitHub (more reliable source)
  ansible.builtin.get_url:
    url: "https://github.com/jpt/barlow/archive/refs/heads/master.zip"
    dest: "{{ temp_font_zip_path }}"
  register: font_download

- name: Extract Barlow font files
  ansible.builtin.unarchive:
    src: "{{ temp_font_zip_path }}"
    dest: "{{ temp_font_dir_path }}"
    remote_src: yes
  register: unarchive_result

- name: Create system font directory for Barlow
  ansible.builtin.file:
    path: /usr/local/share/fonts/truetype/barlow
    state: directory
    mode: '0755'

# GitHub repository has fonts in the 'fonts/otf' and 'fonts/ttf' directories
- name: Copy Barlow font files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/share/fonts/truetype/barlow/
    mode: '0644'
  loop: "{{ lookup('ansible.builtin.fileglob', temp_font_dir_path + '/barlow-master/fonts/ttf/*.ttf', wantlist=True) }}"

- name: Update font cache
  command: fc-cache -fv
  changed_when: true # Assume cache always needs updating after potential font changes

- name: Remove temporary font directory
  ansible.builtin.file:
    path: "{{ temp_font_dir_path }}"
    state: absent
  when: temp_font_dir_path is defined

- name: Set Barlow as default interface font
  become: no # gsettings should run as the user
  command: gsettings set org.gnome.desktop.interface font-name 'Barlow 11'

- name: Set Barlow as default document font
  become: no # gsettings should run as the user
  command: gsettings set org.gnome.desktop.interface document-font-name 'Barlow 11'

- name: Set Barlow Condensed as default monospace font
  become: no # gsettings should run as the user
  command: gsettings set org.gnome.desktop.interface monospace-font-name 'Barlow Condensed 11'
