---
# tasks file for installing Slack

- name: Ensure dependencies for Slack installation are present
  become: yes
  apt:
    name:
      - curl
      - gpg # Needed for the fallback repository key handling
    state: present

- name: Download Slack .deb package (hardcoded URL)
  become: yes
  get_url:
    url: "https://downloads.slack-edge.com/desktop-releases/linux/x64/4.43.51/slack-desktop-4.43.51-amd64.deb"
    dest: /tmp/slack.deb
    mode: '0644'

- name: Install Slack from downloaded .deb
  become: yes
  apt:
    deb: /tmp/slack.deb
    state: present

