---
# tasks file for installing Slack

- name: Ensure dependencies for Slack installation are present
  become: yes
  apt:
    name:
      - curl
      - gpg # Needed for the fallback repository key handling
    state: present

# Attempt to install via direct .deb download (preferred)
- name: Get the final Slack .deb download URL
  become: no # Doesn't require root
  shell: curl -Ls -o /dev/null -w %{url_effective} "https://slack.com/downloads/instructions/linux?ddl=1&build=deb"
  register: slack_url_result
  args:
    executable: /bin/bash
  changed_when: false
  check_mode: no

- name: Download latest Slack .deb package using the final URL
  become: yes
  get_url:
    url: "{{ slack_url_result.stdout }}"
    dest: /tmp/slack.deb
    mode: '0644'
  when: slack_url_result.stdout is defined and slack_url_result.stdout != ""

- name: Install Slack from downloaded .deb
  become: yes
  apt:
    deb: /tmp/slack.deb
    state: present
  when: slack_url_result.stdout is defined and slack_url_result.stdout != "" # Only install if download URL was found and download likely succeeded

