---
# Ubuntu Setup Playbook
- name: Configure Fresh Ubuntu Installation
  hosts: localhost
  become: yes  # Run tasks with sudo
  tasks:
    # Update all packages
    - name: Update apt cache and upgrade all packages
      apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
        autoclean: yes
      
    # Include Firefox setup tasks from firefox.yml
    - name: Include Firefox setup tasks
      include_tasks: firefox.yml

    
    # Include VS Code setup tasks
    - name: Include VS Code setup tasks
      include_tasks: vscode.yml

    # Include Slack setup tasks
    - name: Include Slack setup tasks
      include_tasks: slack.yml

    # Include GNOME customization tasks
    - name: Include GNOME customization tasks
      include_tasks: gnome.yml

    # Install essential applications
    - name: Install applications
      apt:
        name:
          - tilix
          - docker.io
          - docker-compose
          - vim
        state: present
    
    # Clean up unnecessary packages
    - name: Remove unnecessary packages
      apt:
        autoremove: yes
        purge: yes
